// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
insert into payments(
customer_phone,
amount,
mpesa_reference,
business_id
)values(
$1,$2,$3,$4
)returning id, customer_phone, amount, status, created_at, mpesa_reference, failure_reason, business_id
`

type CreatePaymentParams struct {
	CustomerPhone  string        `json:"customer_phone"`
	Amount         sql.NullInt64 `json:"amount"`
	MpesaReference string        `json:"mpesa_reference"`
	BusinessID     int64         `json:"business_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.CustomerPhone,
		arg.Amount,
		arg.MpesaReference,
		arg.BusinessID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CustomerPhone,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.MpesaReference,
		&i.FailureReason,
		&i.BusinessID,
	)
	return i, err
}
